### ISSUE TITLE
dist (.dmg) file not working

### ISSUE THREAD

**Issue by manuartero** [elisealcala/electron-react-ts#4]
Hi there!  first, thanks for this template repo :) 

- _pre_: dev environment is working as expected 

**Steps to reproduce**

- run `npm run build` 
- run `npm run dist`
- (mac) Open the created file `dist/electron-react-ts-1.0.0.dmg`
- Install as usual (drag to Applications folder)
- Double click over the application "electron-react-ts.app"

**Expected result**
- The React app is shown as in development (showing the message "Hi from a React app")

**Got**
- Empty (white) screen is shown 

----

(xxx stands for the app name)

```
$» npm run dist

> xxx@0.0.1 dist /Users/,,,,
> electron-builder

  • electron-builder  version=22.7.0 os=18.7.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=8.2.2 appOutDir=dist/mac
  • default Electron icon is used  reason=application icon is not set
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                                1) 69C4ED1234CA84F1936AF002AE4997F6FA7A2518 "member: 6EC7DA27-4944-4A02-B14D-96698FE76ECB 68F36EC1-D5FA-4696-B34B-E7D463AB4A76" (CSSMERR_TP_NOT_TRUSTED)
                                                2) BA40C0B9C617A262F6874232F3F8C7ABDB48A349 "member: 6EC7DA27-4944-4A02-B14D-96698FE76ECB 93A3E28C-ED1D-4902-8E6C-C7EA0E467FA0" (CSSMERR_TP_NOT_TRUSTED)
                                                   2 identities found

                                                Valid identities only
                                                   0 valid identities found
  • building        target=macOS zip arch=x64 file=dist/xxx-0.0.1-mac.zip
  • building        target=DMG arch=x64 file=dist/xxx-0.0.1.dmg
  • building block map  blockMapFile=dist/xxx-0.0.1.dmg.blockmap
  • building embedded block map  file=dist/xxx-0.0.1-mac.zip

```

**Comment by manuartero** [comment]
important: maybe it's 100% my fault , maybe I'm missing a step? (this is my first attempt with electron+react)

**Comment by elisealcala** [comment]
Hi @manutero, are you working on the production-config branch right? Let me check and see if I miss something.

**Comment by manuartero** [comment]
Hi again. 

 - In the end I went for [this - giant-size - project ](https://github.com/electron-react-boilerplate/electron-react-boilerplate)
 - Interesting thing is that same problem happened to me!
 - I start digging and end up in [**this fix**](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2525/commits/922c584af5627642c5fcb46bcf92848f75e2c9e1) (( 3 days ago it wasn't merged yet))
- maybe it's related?

Feel free to close this issue if it isn't happening to you :)

Gracias ^.^
